cyralinc/terraform-provider-cyral

README.md, doc/native_credentials_aws_sm.md, doc/templates/native_credentials_aws_sm.md
Added a template configuration that can be used to deploy all elements to use native AWS credentials in a Cyral repository.
The proposed configuration was successfully deployed.
=> ENG-3603: Native credentials using AWS SM

Makefile
=> Build docker

cyral/data_source_cyral_sidecar_template.go
Terraform Provider is not using the logs and metrics integration when creating sidecar, to fix that this code modifies the sidecar template data resource
Executed the unit tests and created a template manually.
=> ENG-5789: Terraform Provider is not using the logs and metrics integration when creating sidecar

.dockerignore, .github/dependabot.yaml, Dockerfile, Makefile, README.md, cloudbuild.release.yaml, cloudbuild.yaml, docker-compose.yaml
> Added dockerfile, cloudbuild, linting & dependabot
> Built image and tested
=> ENG-6072: Added dockerfile, cloudbuild, linting & dependabot

Dockerfile
> Fix docs directory rename
> Built docker image
=> ENG-6072: Fix docs directory rename

README.md, cyral/data_source_cyral_sidecar_cft_template_test.go, cyral/resource_cyral_datamap_test.go, cyral/resource_cyral_policy_rule_test.go, cyral/resource_cyral_repository_binding_test.go, cyral/resource_cyral_sidecar.go, cyral/resource_cyral_sidecar_credentials_test.go, cyral/resource_cyral_sidecar_test.go, docs/resource_sidecar.md
Add previously removed parameter to control sidecar deployment method (`deployment_method`).
=> ENG-6066: Add parameter to control sidecar deployment method

Makefile, cyral/resource_cyral_sidecar.go, cyral/resource_cyral_sidecar_test.go
Add sidecar user endpoint as a parameter for sidecar resource.
Documentation updated in #131 (see a8f339822b77d07317b58c21a721c5da2a181bee).
Closes #122.
Pass unit tests and manual e2e tests.
=> Add sidecar user endpoint

docs/data-sources/sidecar_cft_template.md, docs/resources/datamap.md, docs/resources/integration_idp_aad.md, docs/resources/integration_idp_adfs.md, docs/resources/integration_idp_forgerock.md, docs/resources/integration_idp_gsuite.md, docs/resources/integration_idp_okta.md, docs/resources/integration_idp_ping_one.md, docs/resources/repository_local_account.md, docs/resources/role.md, docs/resources/role_sso_groups.md
Some type sets arguments were flattened in the docs. This fix address these documentation issues.
Closes #79.
NA
=> Fix wrong flattened resources in docs

client/validation.go
Denodo was missing from the valid values map so I added it
- [ x ] Bug fix (non-breaking change that fixes an issue)
=> Added denodo to the validValues map

docs/resources/repository_binding.md
demo in docs said listener_port but the variable inside repos is called port
- [ x ] Bug fix (non-breaking change that fixes an issue)
=> Changed listener_port to port so the demo works

cyral/model_cyral_integration_pager_duty.go, cyral/resource_cyral_integration_pager_duty.go, cyral/resource_cyral_integration_pager_duty_test.go
Fix PagerDuty resource and `TestAccPagerDutyIntegrationResource` test, updating it with the new `/confExtensions` endpoint.
Manual and automated tests.
=> ENG-8077: Fix PagerDuty resource due to confExtensions breaking changes

.github/workflows/release.yml, CHANGELOG.md, docker-compose.yaml
Updates hadolint, gorelease and go version in order to fix build issues.
Tested builds with RC tags and checked linter execution locally.
=> Update hadolint, gorelease and go version

cyral/resource_cyral_repository.go, cyral/resource_cyral_repository_test.go, docs/resources/repository.md
> Add labels in our repository and update the tests to apply this configs
> Update the file resource_cyral_repository_test.go with some labels and run tests
=> ENG-8360:  Add labels to cyral_repository

cyral/resource_cyral_policy_rule.go, docs/resources/policy_rule.md
> Policy Rules does not support setting 'any' for data field, for this reason I create a documentation explain how we can set `any` in data field.
> Create the resource using terraform provider
=> ENG-8423: Update docs on how to set policy rule for any data field

client/client.go, client/client_test.go, cyral/data_source_cyral_sidecar_cft_template.go, cyral/resource_cyral_sidecar.go, cyral/resource_cyral_sidecar_credentials.go, cyral/utils.go
- Fixes #15
- Fixes #88
- Fixes #171
For every issue mentioned above, checked that they were failing for main branch, and after this PR's changes they were fixed.
For sidecar_cft_template specifically, I checked that every parameter was correctly being injected into the downloaded CFT, so no previous functionality was broken.
=> ENG-8419: Bug fixes for Terraform provider to be released in v2.6.0

CHANGELOG.md
=> v2.6.0 - Update change log

CHANGELOG.md, docs/resources/integration_idp_okta.md, templates/resources/integration_idp_okta.md.tmpl
Adjust documentation due to change in IdP Okta module name change.
NA
=> Fix repository name for IdP Okta module

cyral/data_source_cyral_integration_idp.go
Simplify filtering conditionals
=> Simplify filtering conditionals

examples/resources/cyral_datalabel/resource.tf, examples/resources/cyral_repository_datamap/resource.tf, examples/resources/cyral_repository_local_account/resource.tf
Add a few missing examples.
N/A. Documentation only.
=> Add some examples

cyral/resource_cyral_sidecar.go, cyral/resource_cyral_sidecar_test.go, docs/resources/sidecar.md
Add single container type to sidecar resource
Manual and automated tests.
=> Add single container type to sidecar resource

cyral/resource_cyral_repository.go, cyral/resource_cyral_repository_test.go
Fixes issue [268](https://github.com/cyralinc/terraform-provider-cyral/issues/268).
Manually test the configs presented in the issue. Also, add an ACC test that captures the issue. The TestAccRepositoryResource test is passing.
=> ENG-9133: Fix issues with repository resource properties

cyral/resource_cyral_repository.go, cyral/resource_cyral_repository_test.go
Fixes issue:
- #268 
Manually test the configs presented in the issue. Also, add an ACC test that captures the issue. The TestAccRepositoryResource test is passing.
=> ENG-9133: Fix issue with repository resource properties

CHANGELOG.md
Update CHANGELOG for new patch version (`v2.7.2`)
=> v2.7.2 - Update CHANGELOG

cyral/resource_cyral_repository_test.go
=> ENG-9133: Fix ACC test changes after merging fix

cyral/data_source_cyral_integration_idp.go, cyral/model_integration_idp.go, cyral/resource_cyral_integration_idp_test.go, cyral/resource_cyral_repository_network_access_policy_test.go, cyral/resource_cyral_role_sso_groups.go, cyral/resource_cyral_role_sso_groups_test.go, cyral/resource_cyral_role_test.go, cyral/sweep_test.go, cyral/testutils.go, cyral/utils.go, cyral/utils_api.go
This PR fixes some flaky tests for `TestAccRepositoryNetworkAccessPolicyResource`.
This PR also adds sweepers for IdP integrations and roles, and does some refactoring on the role-related tests.
The repository network access policy test is passing consistently.
=> ENG-9548: Fix acceptance tests for network access policy

scripts/3.0-migration.sh
edited a minor typo in migration script 
- [x ] All tests related to the changed code pass in development
=> ENG-9929: typo edit in migration script

CHANGELOG.md, cyral/resource_cyral_repository_conf_analysis.go, cyral/resource_cyral_repository_conf_analysis_test.go, docs/guides/3.0-migration-guide.md, docs/resources/repository_conf_analysis.md, examples/resources/cyral_repository_conf_analysis/resource.tf, templates/guides/3.0-migration-guide.md.tmpl
This PR renames parameter `rewrite_on_violation` in resource `cyral_repository_conf_analysis` to `enable_dataset_rewrites`.
This PR also corrects some v3 documentation.
All Acceptance tests are passing.
=> ENG-10012: Remove rewrite_on_violation, add enable_dataset_rewrites

cyral/resource_cyral_sidecar.go, cyral/resource_cyral_sidecar_test.go, docs/resources/sidecar.md
> Adding support for `linux` as a `deploymentMethod` for a sidecar resource
> make successfully passes sidecar resource test
=> ENG-10073: Adding support for linux sidecar deployment

cyral/data_source_cyral_sidecar_cft_template.go, cyral/resource_cyral_sidecar.go, cyral/resource_cyral_sidecar_test.go
ENG-10171: Sidecar resource is throwing nil pointer error when reading properties
This PR fixes the nil `properties` issue for both the `cyral_sidecar` resource and the `cyral_sidecar_cft_template` datasource.
Running all the automated tests and doing manual e2e tests.
=> ENG-10171: Fix sidecar resource nil properties issue

scripts/2.X-4.0-migration.sh, scripts/3.0-migration.sh, scripts/4.0-migration.sh
Escape double quotes in resource names and remove them for resource creation as they are not supported. Use terraform state rm 'string_with_all_resources' instead of for loops with terraform state rm individual_resource
Tested with a new tf script that defines the resource names with double quotes, as well as old scripts without double quotes in their name
=> Improve migration scripts

cyral/resource_cyral_sidecar_listener.go, docs/guides/4.0-migration-guide.md, docs/resources/repository_access_gateway.md, docs/resources/repository_binding.md, docs/resources/sidecar_listener.md, examples/resources/cyral_repository_access_gateway/resource.tf, examples/resources/cyral_repository_binding/resource.tf, examples/resources/cyral_sidecar_listener/resource.tf, scripts/2.X-4.0-migration.sh, scripts/4.0-migration.sh, templates/guides/4.0-migration-guide.md.tmpl
> Jira: https://cyralinc.atlassian.net/browse/ENG-10769
Add information to migration guides (v3 and v4) explaining that the control plane’s data will be migrated automatically during the upgrade and the migration script in the Terraform provider is only there to help migrating the customer’s Terraform scripts.
Add examples to migration guides (v3 and v4) showing how the replaced resources looked like and how they will look like in the new resources for a given scenario. There is no need to exemplify new features and just mentioning that “More information on the new features can be found in the new resources” (or something similar to this statement).
Provide realistic examples to the resources changed in v4, specially for the sidecar listener as it will not work as it is written today.
Fix …
=> ENG-10769: Doc changes and Changes to 4.0 script

docs/guides/3.0-migration-guide.md, docs/guides/4.0-migration-guide.md, scripts/2.X-4.0-migration.sh, scripts/3.0-migration.sh, templates/guides/3.0-migration-guide.md.tmpl, templates/guides/4.0-migration-guide.md.tmpl
ENG-10090: [Terraform] Create tool for migrating terraform files
Update migration scripts with identity map fix and update guides.
Tested both `3.0-migration.sh` and `2.X-4.0-migration.sh` migration scripts on a Kubernetes CP.
=> ENG-10090: Update migration scripts with identity map fix and update guides.

docs/guides/3.0-migration-guide.md, scripts/3.0-migration.sh, templates/guides/3.0-migration-guide.md.tmpl
ENG-10090: Fix identity map issues on 3.0-migration script
Tested running the script against a terraform state with identity maps and local accounts configured using provider `v2.11.1`.
=> ENG-10090: Fix identity map issues on 3.0-migration script

docs/guides/3.0-migration-guide.md, docs/index.md, templates/index.md.tmpl
Fix a broken link to our change log in the Terraform registry documentation.
NA
=> Fix broken link and update docs

cyral/resource_cyral_repository.go, docs/resources/repository.md
Improve `cyral_repository` docs improving `dynamic` and `mongodb_settings` attributes.
NA
=> Improve cyral_repository docs

docs/index.md, templates/index.md.tmpl
Updates the docs index to add a reference to the migration guide.
NA
=> Update docs index with migration guide

cyral/data_source_cyral_sidecar_bound_ports_test.go, cyral/data_source_cyral_sidecar_cft_template_test.go, cyral/data_source_cyral_sidecar_id_test.go, cyral/data_source_cyral_sidecar_instance_ids_test.go, cyral/resource_cyral_repository_access_gateway_test.go, cyral/resource_cyral_repository_binding_test.go, cyral/resource_cyral_sidecar.go, cyral/resource_cyral_sidecar_credentials_test.go, cyral/resource_cyral_sidecar_listener_test.go, cyral/resource_cyral_sidecar_test.go, cyral/testutils.go, docs/resources/sidecar.md
=> ENG-11522: Add sidecar log integration ID

cyral/resource_cyral_sidecar.go, docs/resources/sidecar.md
Deprecation notice for `cyral_sidecar.certificate_bundle_secrets`.
NA
=> ENG-11753: Add deprecation notice

docs/guides/setup_cp_and_deploy_sidecar.md, docs/resources/integration_logging.md, docs/resources/repository.md, examples/guides/setup_cp_and_deploy_sidecar.tf, templates/guides/setup_cp_and_deploy_sidecar.md.tmpl, templates/resources/integration_logging.md.tmpl, templates/resources/repository.md.tmpl
Update guide `Create an AWS EC2 sidecar to protect PostgreSQL and MySQL databases`  to the latest version of the TF provider and also the dependent TF modules.
Deployed each of the guides to test.
=> Update guides to provider 4.0

cyral/resource_cyral_sidecar.go, cyral/resource_cyral_sidecar_test.go, cyral/testutils.go, docs/guides/mongodb_cluster_okta_idp.md, docs/guides/setup_cp_and_deploy_sidecar.md, docs/guides/smart_ports.md, docs/resources/integration_logging.md, docs/resources/sidecar.md, examples/guides/mongodb_cluster/okta_idp_sidecar.tf, examples/guides/setup_cp_and_deploy_sidecar.tf, examples/guides/smart_ports_1.tf, examples/guides/smart_ports_2.tf, examples/resources/cyral_integration_logging/cloudwatch.tf, examples/resources/cyral_integration_logging/fluent-bit.tf
As title. Also deprecate log_integration_id.
TODO
=> ENG-11740: Add activity and diagnostic log ID for sidecar.

cyral/data_source_cyral_repository.go, cyral/resource_cyral_repository_access_rules.go, docs/data-sources/repository.md, docs/resources/repository_access_rules.md, examples/data-sources/cyral_repository/data-source.tf
Documentation improvements for the following items:
* `data.cyral_repository`
* `resource.repository_access_rules`
NA
=> Docs improvements

cyral/core/README.md
Fix a missing reference in `cyral/core/README.md`.
NA
=> Fix missing reference in cyral.core docs

.github/workflows/release.yml, .goreleaser.yml
Fix deprecation messages in the release flow:
* `skip`: https://goreleaser.com/deprecations/#-skip
* `rm-dist`: https://goreleaser.com/deprecations/#-rm-dist
NA
=> Fix deprecation messages in the release flow

.github/workflows/release.yml
=> Change PASSPHRASE -> GPG_PASSPHRASE

cyral/internal/repository/accessrules/resource.go, docs/resources/repository_access_rules.md
=> Document access rule order better

docs/resources/repository_access_gateway.md, examples/resources/cyral_repository_access_gateway/resource.tf
=> minor doc fix

cyral/internal/repository/confanalysis/model.go, cyral/internal/repository/confanalysis/resource.go, cyral/internal/repository/confanalysis/resource_test.go, docs/resources/repository_conf_analysis.md, examples/resources/cyral_repository_conf_analysis/resource.tf
ENG-14573: Add knowledge of mask_all_occurrences config field
=> ENG-14573: Add knowledge of mask_all_occurrences config field

CHANGELOG.md
Update changelog to document changes in (upcoming) release 4.15.0
Rendered changelog file in browser to ensure it renders correctly.
=> v4.15.0 - Update change log

CHANGELOG.md, cyral/core/README.md
Add information about how to use gRPC to implement a resource.
not required.
=> Improve developer documentation

LICENSE-3RD-PARTY.txt
Add license file acknowledging use of third party libraries.
Not needed
=> Add acknowledgements for imported libraries
