cyralinc/terraform-provider-cyral

README.md, scripts/create-service-account-keycloak.sh
Changes service account creation script to prompt for user input and to check for errors at each step. Changes README to suggest using the script instead of having the script in the markdown itself.
The script asks the user for both the CP target and the token, but takes prioritarely from environment variables named `CONTROL_PLANE` and `TOKEN`. The token is to be inserted without the `Authorization: Bearer` because the script already handles that.
Closes #54
Created a service account using both the prompted and the env var based approaches, did it successfully. Errors cause errors and are properly printed on the screen.
Did not test the changes to the README because the script is not on the `main` branch, but should work once it is.
=> Changes keycloak service account initialization script

cyral/data_source_cyral_sidecar_template.go, cyral/data_source_cyral_sidecar_template_test.go
Add missing `helm3` support to data source `cyral_sidecar_template`.
Changes covered by unit tests. Also tested in an existing cluster.
=> ENG-5655: Add missing helm3 support

doc/resource_repository_conf_auth.md
Remove extraneous comma in `cyral_repository_conf_auth` docs. Closes #70.
No tests required as this is just a fix for existing docs.
=> Remove extraneous comma in cyral_repository_conf_auth docs

README.md
This PR is intended to fix the parameters of 'cyral' provider specified in the README.md, replacing 'auth0_domain' and 'auth0_audience' with 'client_id' and 'client_secret'. The PR also corrects a typo in the CCN label for the datamap resource.
=> Fixes README.md with correct parameters for cyral provider

cyral/data_source_cyral_saml_certificate_test.go
Temporarily disabling `TestAccSAMLCertificateDataSource` until we fix the SAML integration.
=> Temporarily disable test

docs/resources/integration_splunk.md, docs/resources/repository.md, docs/resources/repository_binding.md, docs/resources/repository_conf_auth.md
Using for_each seems to provide better documentation and does not result in index-based changes
impacting plans.
This updates the examples in the documentation to use `for_each` instead of `count`.  In general, 
we've found this to be more resilient as well as provide self-documentation.
Documentation change - visually reviewed.
=> docs: update examples to use for_each instead of count

Makefile, README.md, cyral/provider.go, cyral/provider_test.go, cyral/resource_cyral_datamap_test.go, cyral/resource_cyral_integration_datadog_test.go, cyral/resource_cyral_integration_elk_test.go, cyral/resource_cyral_integration_hcvault_test.go, cyral/resource_cyral_integration_logstash_test.go, cyral/resource_cyral_integration_looker_test.go, cyral/resource_cyral_integration_okta_test.go, cyral/resource_cyral_integration_pager_duty_test.go, cyral/resource_cyral_integration_slack_alerts_test.go, cyral/resource_cyral_integration_splunk_test.go, cyral/resource_cyral_integration_sumo_logic_test.go, cyral/resource_cyral_integration_teams_test.go, cyral/resource_cyral_policy_rule_test.go, cyral/resource_cyral_policy_test.go, cyral/resource_cyral_repository_binding_test.go, cyral/resource_cyral_repository_conf_auth_test.go, cyral/resource_cyral_repository_identity_map_test.go, cyral/resource_cyral_repository_local_account_test.go, cyral/resource_cyral_repository_test.go, cyral/resource_cyral_sidecar_test.go
1. Add variable to allow direct assignments to `provider.control_plane` variable: `CYRAL_TF_CONTROL_PLANE`;
2. Replace test env var `CYRAL_TF_CP_URL` by `CYRAL_TF_CONTROL_PLANE`;
3. Remove deprecated code.
Closes #138.
Successful run of existing tests.
=> Add CYRAL_TF_CONTROL_PLANE env var support

cyral/resource_cyral_sidecar.go
This PR fixes an issue with the sidecar resource about returning a `500` error when the sidecar was actually not found. So the fix was basically handling the error and just removing the resource from the state. Notice that, currently, the sidecar API always returns a status code of `500` for every error, so its not possible to distinguish if the error returned is related to a `404 Not Found` or not by its status code. This way, a workaround for that is to check if the error message matches a 'Failed to extract info for wrapper' message, since thats the current message returned when the sidecar is not found. Once this issue is fixed in the sidecar API, we should handle the error here, on the Terraform Provider side, by its status code, and only remove the resource from the state …
=> ENG-7416: Fixes issue about missing sidecar returning 500 error

cyral/resource_cyral_repository_identity_map.go
- Changes identity map resource to delete previous resource and create new one on update
- CHanges id for identity map resource to be independent of fields
Created, updated, deleted identity maps with valid and invalid parameters, all worked as intended.
=> ENG-7170: Terraform provider creates a new identity map instead of updating old one when state changes

Makefile
This PR updates the tests timeout to 20m so that all of the tests can run in the e2e-tests without causing a panic.
Tested all the tests running `make`.
=> Fix tests timeout

docs/resources/repository_binding.md
Modified the doc example from 
...
sidecar_id    = cyral_resource.SOME_SIDECAR_RESOURCE_NAME.id
to 
...
sidecar_id    = cyral_sidecar.SOME_SIDECAR_RESOURCE_NAME.id
- [ x ] Bug fix (non-breaking change that fixes an issue)
ran terraform apply with the new change and it rolled out correctly
=> Change cyral_repository to cyral_sidecar for the sidecar_id

cyral/resource_cyral_policy.go, docs/resources/policy.md
The field `property` is available through the Terraform provider as part of the `policy` resource, but it is not in use by the backend. To avoid breaking compatibility we are deprecating it for now and it will be removed in the next major release.
Manual deployment of policy resource with local provider. Deprecation warning was displayed as expected.
=> ENG-8168: Deprecate properties field from policy resource

cyral/resource_cyral_repository_binding.go, cyral/resource_cyral_repository_binding_test.go, docs/resources/repository_binding.md, docs/resources/repository_conf_auth.md
This PR adds a new argument named `select_sidecar_as_idp_access_gateway` to the repo binding resource, which is responsible for enabling/disabling Access Gateway for the bound sidecar. It also fixes an issue of not being able to delete repo bindings that had an Access Gateway sidecar.
Manual and automated tests
=> ENG-8182, ENG-8215: Add Access Gateway support for repo binding resource

.gitignore, cyral/provider.go, cyral/resource_cyral_repository_identity_map.go, cyral/resource_cyral_repository_identity_map_test.go, cyral/resource_cyral_repository_local_account.go, cyral/resource_cyral_repository_local_account_test.go, docs/resources/repository_local_account.md
ENG-8392: Terraform provider - add resource for k8s secrets local account
- Add support for Kubernetes Secret
- Deprecate `enviroment_variable` field since it contains a typo
- Fix issue with `repository_id` by adding ForceNew to this field
- Fix some details in docs.
Manual and automated tests
=> ENG-8392: Change repo local account resource to support Kubernetes Secret

Makefile, client/client.go, client/client_test.go, cyral/provider.go, docs/index.md
> Create field in our provider that support TLS option and Add support to M1 architecture in macOs
> Create an resource in a CP that don't have a valid cerificate, and create an repository and policies.
Runned all the tests
=> ENG-8345: Support different TLS options

cyral/resource_cyral_repository_local_account.go, cyral/resource_cyral_repository_local_account_test.go, docs/resources/repository_local_account.md
ENG-8591: Terraform provider - Update repo account resource to support GCP Secret Manager
Manual and automated tests
=> ENG-8591: Change repo account resource to support GCP Secret Manager

cyral/data_source_cyral_saml_certificate.go, cyral/resource.go, cyral/resource_cyral_integration_datadog.go, cyral/resource_cyral_integration_elk.go, cyral/resource_cyral_integration_hcvault.go, cyral/resource_cyral_integration_idp.go, cyral/resource_cyral_integration_logstash.go, cyral/resource_cyral_integration_looker.go, cyral/resource_cyral_integration_okta.go, cyral/resource_cyral_integration_pager_duty.go, cyral/resource_cyral_integration_slack_alerts.go, cyral/resource_cyral_integration_splunk.go, cyral/resource_cyral_integration_sumo_logic.go, cyral/resource_cyral_integration_teams.go, cyral/resource_cyral_repository_conf_auth.go, cyral/resource_cyral_repository_identity_map.go, cyral/resource_cyral_repository_local_account.go, cyral/resource_cyral_role_sso_groups.go
ENG-8610: Terraform provider: Creating 30+ repos will fail when creating identity map with okta as idp
This PR fixes an issue where resource instances of the same type were sharing the same memory address for the request/response payloads, this was causing data inconsistency between the resource instances. This fix also includes some code refactoring in the provider's internal structure (addressing issue #196). All of these changes are backward compatible.
Manual and automated tests. All tests are passing as expected, since these changes are supposed to be backward compatible.
=> ENG-8610: Fix memory referencing issue and refactor resources

Dockerfile, cyral/resource_cyral_datamap.go, cyral/resource_cyral_repository.go, cyral/resource_cyral_repository_test.go, docs/resources/datamap.md, docs/resources/repository.md
Adds parameters necessary to support MongoDB replica sets to the cyral_repository resource.
Added ACC test that covers added parameters.
- Deploy a Terraform config with this version of the provider containing a cyral_repository resource like the following
```hcl
resource "cyral_repository" "repo1" {
host = "mongo-host-1"
port = 27017
type = "mongodb"
name = "mongo-repo-1"
properties {
mongodb_replica_set {
max_nodes = 2
replica_set_id = "replica-set-id-1"
}
}
}
```
- Doing GET v1/repos returns the same results as if the replica set had been created from the UI.
=> ENG-6069: Support MongoDB repository replica sets

.github/workflows/release.yml
The current action used to import GPG key was deprecated ([See](https://github.com/hashicorp/ghaction-import-gpg/issues/11#issuecomment-1185107410)). A substitute for that is to use the [crazy-max/ghaction-import-gpg](https://github.com/crazy-max/ghaction-import-gpg) action instead.
OBS: This fix will need to be cherry-picked to the main branch
=> ENG-8942: Change action used to import GPG key

docs/guides/setup_cp_and_deploy_sidecar.md
Fix an invalid variable name in the guide to setup CP and deploy sidecar to AWS.
Deployed the actual example and it worked.
=> Fix typo in guide to setup CP and deploy sidecar to AWS

cyral/resource_cyral_repository.go, docs/data-sources/repository.md, docs/resources/repository.md
Add `dynamodb` as a supported database.
Passed acceptance tests as follows:
```
=== RUN   TestAccRepositoryResource
--- PASS: TestAccRepositoryResource (11.24s)
PASS
ok      github.com/cyralinc/terraform-provider-cyral/cyral      11.532s
```
=> ENG-8321: Add support for dynamodb

docs/index.md, templates/index.md.tmpl
Fix dated docs which used the wording `Service Account` where we now refer as `API Client Credentials` in the UI.
NA
=> Update credentials doc

cyral/resource_cyral_datalabel_test.go, cyral/resource_cyral_sidecar_test.go
The ACC tests were failing due to the Import test in the Data Label resource -- file `cyral/resource_cyral_datalabel_test.go`. After merging multiple PRs, specifically #260 and #261, unfortunately we missed this detail when solving the conflicts between the PRs.
I took the opportunity to correct a redundant ACC test we had added for the `cyral_sidecar` resource. The changes in `cyral_resource_sidecar_test.go` are not necessary for the fix, it is just to improve test quality there.
Ran all ACC tests against a clean Control Plane with version `v2.34.1`. All ACC tests are passing.
=> ENG-9128: Fix ACC tests

examples/guides/mongodb_cluster_okta_idp_sidecar.tf
For mongoDB port range, explain that the port number you pass as the 
second argument to the `mongodb_ports = range()` function is not
included in the range. This is as designed by Terraform, but users 
are often surprised by it.
This is a bug fix (non-breaking change that fixes an issue).
=> Explain setting max value of port range. CS-192.

cyral/resource_cyral_repository_user_account.go
A race condition was caused during exactltyOneOf validation by [this line](https://github.com/cyralinc/terraform-provider-cyral/blob/30c18a231452631a0166e63fbb162bb3094ed9dd/cyral/resource_cyral_repository_user_account.go#L324), due to the fact that the slice was nor allocated. Allocating the slice, such that underlying array remains constant, removed the race condition. 
Please see [this slack thread](https://cyralinc.slack.com/archives/C01NQPCDRTQ/p1664820750286589) for more info. 
> This was tested against a CFT based CP.
=> ENG-9385: Fix race condition in user accounts test

cyral/resource_cyral_repository_local_account.go, cyral/resource_cyral_repository_local_account_test.go, docs/resources/repository_local_account.md, examples/resources/cyral_repository_local_account/resource_automatic_approval.tf, templates/resources/repository_local_account.md.tmpl
This PR adds the argument `config` in the resource `cyral_repository_local_account`. `config` has a nested schema with arguments `auto_approve_access` and `max_auto_approve_duration`.
Acceptance tests were added and are passing.
- Create local account without `config`
- Create local account with `config` but no `auto_approve_access` -- errs, as expected
- Create local account with `config` and `auto_approve_access` set to false 
- Try `terraform apply` again and make sure plan is empty
- Create local account with `auto_approve_access = true` and `max_auto_approve_duration = "PT4S"`, update to `PT5M`
- In every step, make sure terraform plan is empty
- Check if UI matches config
- Also tried updating `auto_approve_access` from `true` to `false`
- Destroy worked for all cases above
=> ENG-9704: Add support for local account automatic approvals

docs/guides/mongodb_cluster_okta_idp.md, docs/guides/native_credentials_aws_sm.md, docs/guides/setup_cp_and_deploy_sidecar.md, examples/guides/mongodb_cluster_okta_idp_okta.tf, examples/guides/mongodb_cluster_okta_idp_versions.tf, examples/guides/native_credentials_aws_sm.tf, examples/guides/setup_cp_and_deploy_sidecar.tf
This PR adds standardization to use the `~>` version constraint in the guides, to avoid having user deployments breaking due to v3 changes.
I only tested the AWS SM guide, in which I added a `terraform` block and completed the `provider` block which were missing. I did not test the other guides because the changes made are not supposed to break anything, so I only did `terraform init` to make sure there are no typos.
=> ENG-9629: Use version constraint ~> for guides (v2)

cyral/resource_cyral_policy_rule.go, cyral/resource_cyral_policy_rule_test.go
Same as #301 , but this is a fix on top of version 2 of the TF provider.
Manually tested that the issue does not happen after the changes. Acceptance test TestAccPolicyRuleResource is passing.
=> ENG-9835: Policy rule identities field should be omitted by default (v2)

cyral/resource_cyral_policy_rule.go, cyral/resource_cyral_policy_rule_test.go
This PR solves issue #300 
Also, this PR adds the capability of the policy rule to ignore a non-existent policy rule on deletion (when received a 404). I have encountered this problem in the past, so decided to include this fix in the PR.
Manually checked that the issue is not happening anymore.
Also added acceptance tests. All acceptance tests are passing after the changes.
=> ENG-9835: Policy rule identities field should be omitted by default

cyral/resource_cyral_role.go, cyral/resource_cyral_role_test.go, docs/resources/role.md, examples/resources/cyral_role/resource.tf
Jira: https://cyralinc.atlassian.net/browse/ENG-10094
After cleaning up some permissions that are no longer used, some Terraform tests broke. It turns out that the Cyral Role Terraform contains direct references to Cyral Permissions. This PR removes the 'View Sidecars and Repositories' permission that is now being granted to all API clients, users and groups. It also adds some new permissions that had not yet been added. 
=> ENG-10094: Deprecate & Update Cyral Permissions in for Cyral Roles

cyral/resource_cyral_role.go, cyral/resource_cyral_role_test.go, docs/resources/role.md, examples/resources/cyral_role/resource.tf
Jira: https://cyralinc.atlassian.net/browse/ENG-10094
After cleaning up some permissions that are no longer used, some Terraform tests broke. It turns out that the Cyral Role Terraform contains direct references to Cyral Permissions. This PR deprecates the 'View Sidecars and Repositories' permission that is now being granted to all API clients, users and groups.
=> ENG-10094: Deprecate 'View Sidecars and Repositories'

scripts/3.0-migration.sh
Improved the script to make less calls to terraform show -json. Also I modified the way we create the tf_state array to only list cyral_repository_identity_map and cyral_repository_local_account. From a performance standpoint I tested locally migrating only 1 repo with 1 account and 1 identity map:
OLD bash ./3.0-migration.sh  5.87s user 1.28s system 114% cpu 6.235 
NEW bash ./3.0-migration.sh  1.05s user 0.25s system 97% cpu 1.332 total
Test is still running locally, but with my 6000 resource terraform script each resource takes 2-4 seconds vs 10+ on the previous script
=> Modified the script to call terraform show less

cyral/resource_cyral_repository.go, docs/data-sources/repository.md, docs/resources/repository.md
Removed mentions of cassandra and bigquery as they are not supported as repo types
Removed the unsupported repos from the doc and the go file, doc no longer shows them :P
=> clean up supported repos

docs/guides/mongodb_cluster_okta_idp.md, docs/guides/setup_cp_and_deploy_sidecar.md, examples/guides/mongodb_cluster_okta_idp_sidecar.tf, examples/guides/setup_cp_and_deploy_sidecar.tf
These fields were initially deprecated in sidecar v3.0.0 and will be removed in a future release
No tests performed.
=> ENG-10518: Remove references to deprecated fields mongodb_port_alloc_range_low/high

cyral/resource_cyral_repository_access_gateway.go, docs/resources/repository_access_gateway.md
> The access gateway resource was written before a validation was added, and the tests are now failing. See this [E2E test report](https://00f74ba44bff38344111bc65e7eedffdc64bd22884-apidata.googleusercontent.com/download/storage/v1/b/cyral-artifacts-dev/o/nightly-e2e-tests%2Freport.2cd2d3e6-f908-4213-bbae-933ab09e513f.html?jk=AFshE3UjCbwRGL4uImJD_qVJ82cGBhmvupcRX1jQlTKS5uiPNZKFed3qxZaB7h5PtawRoBZe3tbmRChCBBZsh8_l7x7riP08Csehgwe7jgAc_xO_5rekfzQx1Le6iLyOk4XDPaotKtteEa_UXjWIAMBTg1CWj1KMoY6ORPWlTIgWBcuAG3Bm0U_YoM8_y5mrxwO8bPwTDlWRDkAs1t9Chrsq0wfW6juLK3gmUqnXatr_o1KFw3ZRMQwCXbIC9u9HnuivMzatooub2bPDGIC0IIsfEkkA2MKlsP9Lv0_oA_OppK8386C33T5wnmE_mU3snN63I2r_uR9fylkRQaCQ2yW4a22DTV8a-UXagk3qhvcex3F-p8cdSK1mJ4TWbKPkSNpfgrjARdGmZ6gFPy5YjSF0TyDE70ltfXom4r4mXzvfM4FcbsEKzVGMcGD-RWwczeLl1XeW_oMkR7iWNOkPfihJ …
=> ENG-10659: Adding Force New Directives to Access Gateway resource

cyral/data_source_cyral_repository_test.go, cyral/resource_cyral_repository.go, cyral/resource_cyral_repository_network_access_policy.go, cyral/resource_cyral_repository_test.go, cyral/testutils.go, docs/data-sources/repository.md, docs/guides/4.0-migration-guide.md, docs/guides/native_credentials_aws_sm.md, docs/resources/repository.md, examples/data-sources/cyral_repository/data-source.tf, examples/guides/4.0-migration/example-resources-v4.tf, examples/guides/native_credentials_aws_sm.tf, examples/resources/cyral_repository/resource.tf
Fix a bug that allows empty blocks for `cyral_repository. mongodb_settings` when `cyral_repository.type = mongodb`.
Acceptance tests were executed against `stable` and all tests passed.
=> Make mongodb_settings mandatory if cyral_repository.type = mongodb

cyral/data_source_cyral_repository.go, cyral/resource_cyral_repository.go, cyral/resource_cyral_repository_test.go, docs/data-sources/repository.md, docs/resources/repository.md
Repo creation can now take a new optional argument for `MongoDBSettings`, called `SRVRecordName`. This PR updates our TF provider so that it can also use that new argument.
Using a local CP I created a replica set repo with all-dynamic repo nodes, as well as a sharded repo. Both worked fine. Acceptance tests were also updated.
=> ENG-10482: teach Terraform provider about MongoDB SRV Records

cyral/resource_cyral_integration_idp.go
[ENG-11021](https://cyralinc.atlassian.net/browse/ENG-11021): Keycloak doesn't allow Transient NameID Format with SUBJECT Principal Type when creating ADFS IdP
Update the NameID Policy Format default value for ADFS to match fix in the integrations service (See https://github.com/cyralinc/integrations/pull/485).
Related PRs:
- https://github.com/cyralinc/integrations/pull/485
- https://github.com/cyralinc/cyral-docs-v2/pull/295
Tested by running the Acceptance Tests.
[ENG-11021]: https://cyralinc.atlassian.net/browse/ENG-11021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ENG-11021: Update ADFS default value for IdP resource

cyral/resource_cyral_repository_access_rules.go, docs/resources/repository_access_rules.md
Improve the `cyral_repository_access_rules` docs to make clear that users should use the `user_account_id` attribute from `cyral_repository_user_account` instead of `id`.
NA
=> Update cyral_repository_access_rules docs

cyral/resource_cyral_repository_conf_auth.go
Fixes the repository_conf_auth resource re-creation issue by determining the http method (POST or PUT) during the resource creation. For further context see:
https://cyralinc.atlassian.net/browse/ENG-11209: Error when recreating terraform repository_conf_auth resource
Tested the resource recreation manually and ran the automated tests. All tests passed, see the result below:
```log
2023/03/16 18:32:03 [DEBUG] Init NewClient
2023/03/16 18:32:03 [DEBUG] TokenSource: &{0xc0000bcf00 {0 0} <nil>}
2023/03/16 18:32:03 [DEBUG] End NewClient
--- PASS: …
```
=> Update Conf Auth resource to fix recreation issue

Makefile, cyral/resource_cyral_repository_access_rules.go
Due to a backend inconsistency that leaves an empty access rule set behind, the following error could happen:
1. User creates access rules through Terraform;
2. User removes same access rules using the UI;
3. User try to re-create the very same access rules using Terraform and faces a `409` error.
The error is due to the empty access rule set that is left behind by our API. This is going to be fixed and the set will be completely removed, but in order to avoid customers from having this error and not being able to recover, we opted to switch the `POST` to a `PUT` in the access rules creation.
We could use the `POST` back after all customers are migrated to a release that contains the fix informed in the associated Jira ticket.
Ignore the IdP test failure as the test cluster is a previous …
=> ENG-11206: Replace POST by PUT in access rule creation

cyral/resource_cyral_integration_datadog.go, cyral/resource_cyral_integration_elk.go, cyral/resource_cyral_integration_logstash.go, cyral/resource_cyral_integration_looker.go, cyral/resource_cyral_integration_splunk.go, cyral/resource_cyral_integration_sumo_logic.go, docs/resources/integration_datadog.md, docs/resources/integration_elk.md, docs/resources/integration_logstash.md, docs/resources/integration_looker.md, docs/resources/integration_splunk.md, docs/resources/integration_sumo_logic.md
Deprecate the following resources:
`cyral_logging_datadog`
`cyral_logging_elk`
`cyral_logging_logstash`
`cyral_logging_looker`
`cyral_logging_splunk`
`cyral_logging_sumologic`
NA
=> Deprecate old resources

cyral/resource.go, cyral/resource_cyral_integration_idp_saml.go
A missing validation step caused the generic SAML integrations to error out during user log in.
```
2023/07/12 22:57:11 [DEBUG] Init NewClient
2023/07/12 22:57:11 [DEBUG] TokenSource: &{0xc00000ee70 {0 0} <nil>}
2023/07/12 22:57:11 [DEBUG] End NewClient
=== RUN   TestNewClient_WhenTLSSkipVerifyIsDisabled_ThenInsecureSkipVerifyIsFalse
2023/07/12 22:57:11 [DEBUG] Init NewClient
2023/07/12 22:57:11 [DEBUG] TokenSource: &{0xc00000eea0 {0 0} <nil>}
2023/07/12 22:57:11 [DEBUG] End NewClient
--- PASS: TestNewClient_WhenTLSSkipVerifyIsDisabled_ThenInsecureSkipVerifyIsFalse (0.00s)
=== RUN …
```
=> ENG-12107: Add missing validation to idp saml resource

cyral/model_integration_logging.go, docs/resources/integration_logging.md, examples/resources/cyral_integration_logging/fluent-bit.tf
Improves `cyral_integration_logging.es_credentials` description to mention how to use it with unprotected ELK instances.
NA
=> Improve es_credentials description

cyral/data_source_cyral_integration_logging_test.go, cyral/model_integration_logging.go, cyral/resource_cyral_integration_logging.go, cyral/resource_cyral_integration_logging_test.go
Terrraform provider panics when ELK integration creds are not set
Tested different resources manually:
`terraform init/apply` them
`terraform show`
trying only `kibana_url` and `terraform apply/show`
=> ENG-12193: Terrraform provider panics when ELK integration creds are not set

cyral/error_handlers.go, cyral/resource_cyral_integration_datadog.go, cyral/resource_cyral_integration_elk.go, cyral/resource_cyral_integration_hcvault.go, cyral/resource_cyral_integration_idp_saml.go, cyral/resource_cyral_integration_logging.go, cyral/resource_cyral_integration_slack_alerts.go, cyral/resource_cyral_integration_teams.go, cyral/resource_cyral_repository.go, cyral/resource_cyral_repository_access_gateway.go, cyral/resource_cyral_repository_access_rules.go, cyral/resource_cyral_repository_binding.go, cyral/resource_cyral_repository_conf_auth.go, cyral/resource_cyral_repository_network_access_policy.go, cyral/resource_cyral_repository_user_account.go, cyral/resource_cyral_role_sso_groups.go, cyral/resource_cyral_sidecar_listener.go
Add proper error handling for `404` issues during read operations. This is a Terraform best practice to get the provider to signal the necessity to recreate a resource in case it does not exist instead of erroring out.
This scenario explains a recurring issue some of our customers face:
1. User creates a resource in Terraform;
2. User removes the resource manually from the control plane, making the state out-of-sync;
3. User runs `terraform apply`;
4. Our provider returns an error during the read operation as the resource does not exist anymore and aborts Terraform execution.
With this fix, this is what happens:
1. User creates a resource in Terraform;
2. User removes the resource manually from the control plane, making the state out-of-sync;
3. User runs `terraform apply`;
4. Our …
=> Fix error handling in case of states out of sync

cyral/model_policy.go, cyral/resource_cyral_integration_logging_test.go, cyral/resource_cyral_integration_sumo_logic_test.go, cyral/resource_cyral_policy.go, cyral/resource_cyral_policy_test.go, docs/resources/policy.md, examples/resources/cyral_policy/resource.tf
The current policy resource ([cyral_policy](https://github.com/cyralinc/terraform-provider-cyral/blob/main/cyral/resource_cyral_policy.go)) does not have a field for [data label tags](https://cyral.com/docs/v4.7/policy/policy-structure/#the-tags-block-of-a-policy) - it only has a `tags` field that refers to the policy metadata tags. That said, this PR adds a field for data label tags to the `cyral_policy` resource. This PR also fixes the sumologic tests that were failing after an update in the API that validates the sumologic address.
Tested by running automated tests and performing E2E manual tests. Automated tests result:
```log
=== RUN …
```
=> ENG-12334: Add data label tags field to the policy resource

cyral/data_source_cyral_sidecar_cft_template.go, cyral/model_datalabel.go, cyral/resource_cyral_datalabel.go, cyral/resource_cyral_datalabel_test.go, docs/data-sources/sidecar_cft_template.md, docs/resources/datalabel.md, examples/resources/cyral_datalabel/resource.tf
This PR contains the following changes:
- Adds `classification_rule` field to data label resource
- Deprecates `cyral_sidecar_cft_template` data source since it is no longer valid for new sidecars
Automated tests and manual E2E tests. See automated tests result below:
```log
2023/08/08 17:18:42 [DEBUG] Init NewClient
2023/08/08 17:18:42 [DEBUG] TokenSource: &{0xc0000a6d98 {0 0} <nil>}
2023/08/08 17:18:42 [DEBUG] End NewClient
=== RUN …
```
=> ENG-12179: Add classification rule field to data label resource

cyral/model_integration_logging.go, cyral/resource_cyral_integration_logging.go, cyral/resource_cyral_integration_logging_test.go, docs/data-sources/integration_logging.md, docs/resources/integration_logging.md
Fluent Bit's config parsing Go library has proven to be occasionally buggy with regard to validation, so this option allows users to completely bypass config validation primarily in those cases. Note that while this will allow invalid configurations to be saved to the Control Plane, there is no guarantee that such configs will actually work with Fluent Bit. This does not skip the sidecar's Fluent Bit from validating the configuration, and that Fluent Bit's internal parser may still fail during parsing. In that case, logs will just be written to the sidecar's stdout/stderr instead of being shipped to any (mis)configured destinations.
Ran the tests via make. They seem a bit flaky but I saw the tests that I added pass.
=> Add `skip_validate` option to Fluent Bit logging integration resource.

cyral/resource_cyral_integration_logging_test.go, cyral/resource_cyral_repository_conf_auth.go, cyral/resource_cyral_repository_conf_auth_test.go, docs/resources/repository_conf_auth.md
Fix terraform tests that were failing in the E2E tests report. The errors were all related to the tests, so these changes does not have impact on the resource's functionality.
Tested by running automated tests with `make`. See test results below:
```bash
?   	github.com/cyralinc/terraform-provider-cyral	[no test files]
2023/09/19 20:12:47 [DEBUG] Init NewClient
2023/09/19 20:12:47 [DEBUG] TokenSource: &{0xc00013cf00 {0 0} <nil> 0}
2023/09/19 20:12:47 [DEBUG] End NewClient
=== RUN   TestNewClient_WhenTLSSkipVerifyIsDisabled_ThenInsecureSkipVerifyIs …
```
=> Fix terraform tests that were failing in the E2E tests report

cyral/data_source_cyral_sidecar_bound_ports_test.go, cyral/data_source_cyral_sidecar_cft_template.go, cyral/data_source_cyral_sidecar_cft_template_test.go, cyral/data_source_cyral_sidecar_id_test.go, cyral/data_source_cyral_sidecar_instance_ids_test.go, cyral/resource_cyral_sidecar.go, cyral/resource_cyral_sidecar_test.go, docs/data-sources/sidecar_cft_template.md, docs/resources/sidecar.md
> Removing the `helm` deployment type and changing `cloudFormation` to `cft-ec2` to be in line with what is currently used when using the UI.
> Ran `make` locally and the changed tests passed
=> Removing the `helm` and `cloudFormation` sidecar deployment types

docs/resources/rego_policy_instance.md, examples/resources/cyral_rego_policy_instance/resource.tf, templates/resources/rego_policy_instance.md.tmpl
[ENG-12728](https://cyralinc.atlassian.net/browse/ENG-12728): Add terraform examples on how to create rego policies for different templates
Tested the documentation using the [Terraform Doc Preview](https://registry.terraform.io/tools/doc-preview) and also tested the terraform config examples.
[ENG-12728]: https://cyralinc.atlassian.net/browse/ENG-12728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ENG-12728: Add template parameters section to the rego_policy_instance docs

cyral/data_source_cyral_sidecar_instance_stats_test.go
Fix test for `cyral_sidecar_instance_stats` data source so that it works running in parallel with other tests.
Before this fix:
```
Step #4 - "E2E":     data_source_cyral_sidecar_instance_stats_test.go:19: Step 4/4, expected an error with pattern, no match on: Error running apply: exit status 1
Step #4 - "E2E":         
Step #4 - "E2E":         Error: Unable to create sidecar
Step #4 - "E2E":         
Step #4 - "E2E":           with cyral_sidecar.test_sidecar,
Step #4 - "E2E":           on terraform_plugin_test.tf line 2, in resource "cyral_sidecar" "test_sidecar":
Step #4 - "E2E":            2: 	resource "cyral_sidecar" "test_sidecar" {
Step #4 - "E2E":         
Step #4 - "E2E":         error executing POST request; status code: 500; body: "{\"Message\":\"Failed
Step #4 - "E2E": …
```
=> Fix test for cyral_sidecar_instance_stats data source

cyral/resource_cyral_repository_network_access_policy.go, docs/resources/repository_network_access_policy.md, examples/resources/cyral_repository_network_access_policy/resource.tf
Update `cyral_repository_network_access_policy` docs informing about a required `depends_on` relationship to `cyral_repository_conf_auth` that refers to the same repo to avoid errors in `terraform destroy` execution.
This is necessary due to a backend limitation that will be addressed in the future. 
NA
=> Update docs to avoid errors during destroy commands

cyral/internal/sidecar/instance/data_source_cyral_sidecar_instance_stats_test.go, cyral/internal/sidecar/instance/data_source_cyral_sidecar_instance_test.go
Fix expected error message length for failing tests (`TestAccSidecarInstanceStatsDataSource` and `TestAccSidecarInstanceDataSource`). Since the error message returned by the sidecar API was updated, the regex used in these terraform tests was not matching the error anymore due to a line break in the error message. This was fixed by shortening the sidecar id used so that the error message fits in a single line.
Running automated tests, see result below:
```
?   	github.com/cyralinc/terraform-provider-cyral	[no test files]
?   	github.com/cyralinc/terraform-provider-cyral/cyral/core	[no test files]
?   	github.com/cyralinc/terraform-provider-cyral/cyral/core/types/operationtype	[no test files]
? …
```
=> Fix expected error message length for failing tests

docs/guides/iam_auth_rds_pg.md, docs/guides/s3_browser_and_aws_cli.md, examples/guides/iam_auth_rds_pg.tf, templates/guides/iam_auth_rds_pg.md.tmpl
Add new guide for AWS IAM authentication from sidecar to RDS instances.
Guide deployed succesfully.
=> Add AWS RDS IAM auth guide

cyral/internal/repository/data_source_cyral_repository.go, cyral/internal/repository/resource_cyral_repository_test.go, docs/data-sources/repository.md
The [PR](503) that added support for the `flavor` attribute in `cyral_repository.mongodb_settings` missed the respective data source.
```
?       github.com/cyralinc/terraform-provider-cyral/cyral/core [no test files]
?       github.com/cyralinc/terraform-provider-cyral/cyral/core/types/operationtype     [no test files]
?       github.com/cyralinc/terraform-provider-cyral/cyral/core/types/resourcetype      [no test files]
=== RUN …
```
=> Add missing mongodb flavor configuration

CHANGELOG.md, docs/guides/iam_auth_rds_pg.md, templates/guides/iam_auth_rds_pg.md.tmpl
The current version of the docs points to the `arn` as the user name that must be created on the RDS instance, but this approach does not work. The role `name` must be used instead.
The issue was found during tests with the actual guide, so the fix was required to get it running.
=> Fix role name in RDS IAM required permissions

cyral/internal/repository/confauth/resource_cyral_repository_conf_auth.go, docs/resources/repository_conf_auth.md
As title. Part of https://cyralinc.atlassian.net/wiki/spaces/EN/pages/2212921352/Deprecate+IdP+Specification+in+Access+Token+Based+Repo+Authentication
=> ENG-13675: update documentation for identity_provider field

cyral/core/error_handlers.go
Ignore regex error analysis for not found errors when the status code is already `404`.
This makes the TF provider compatible with APIs that had the status code properly fixed in case of resources not found and also for those old APIs that returned `50x` statuses.
Manually tested the code forcing a `404` error in an old API that would normally return a `500`. Also made sure it works properly when returning an actual `500`.
The results of the acceptance tests are as follows:
```
terraform-provider-cyral % make local/test                                                
?       github.com/cyralinc/terraform-provider-cyral/cyral/core [no test …
```
=> Ignore regex analysis for 404 status code

cyral/internal/integration/logging/model.go, docs/resources/integration_logging.md, examples/resources/cyral_integration_logging/fluent-bit.tf
We're going to deprecate ELK in the next major due to inconsistencies/confusion between versions v7/v8, so we need to direct users to migrate to custom logging integration instead.
=> ENG-13977: Add deprecation message in existing ELK Terraform

cyral/internal/repository/useraccount/model.go, cyral/internal/repository/useraccount/resource.go, cyral/internal/repository/useraccount/resource_test.go, docs/resources/repository_user_account.md, examples/resources/cyral_repository_user_account/resource.tf
As title.
```
GOROOT=/usr/local/opt/go/libexec #gosetup
GOPATH=/Users/ccampo/go #gosetup
/usr/local/opt/go/libexec/bin/go test -c -o /Users/ccampo/Library/Caches/JetBrains/IntelliJIdea2024.1/tmp/GoLand/___1resource_test_go.test github.com/cyralinc/terraform-provider-cyral/cyral/internal/repository/useraccount #gosetup
/usr/local/opt/go/libexec/bin/go tool test2json -t /Users/ccampo/Library/Caches/JetBrains/IntelliJIdea2024.1/tmp/GoLand/___1resource_test_go.test -test.v -test.paniconexit0 -test.run ^\QTestAccRepositoryUserAccountResource\E$
=== RUN   TestAccRepositoryUserAccountResource
=== PAUSE TestAccRepositoryUserAccountResource
=== CONT  TestAccRepositoryUserAccountResource
--- PASS: TestAccRepositoryUserAccountResource (31.69s)
PASS
Process finished with the exit code 0
```
=> ENG-14083: Add Azure Key Vault user account auth scheme

docs/resources/policy.md, docs/resources/policy_rule.md, examples/resources/cyral_policy/resource.tf, examples/resources/cyral_policy_rule/resource.tf
Improve examples for resources `cyral_policy` and `cyral_policy_rules` to show a rego policy use case. The current examples just show all fields of the resources and don't show a tangible use case. The goal for this PR is add some meaningful policy that can be read and understood by users.
NA
=> Improve examples for resources policy and policy_rules

cyral/internal/repository/constants.go, cyral/internal/repository/model.go, cyral/internal/repository/resource.go, cyral/internal/repository/resource_test.go, cyral/internal/repository/useraccount/model.go, cyral/internal/repository/useraccount/resource.go, cyral/internal/repository/useraccount/resource_test.go, docs/resources/repository.md, docs/resources/repository_user_account.md
We recently added the capability for Redshift repos to use AWS IAM as the Authentication method between the sidecar and the DB. In order to do this, we added a few fields to the `repo` and the `userAccount` objects, so this PR teaches Terraform about them.
Added a couple new unit tests and they passed.
=> ENG-14270: redshift iam

cyral/internal/repository/confauth/constants.go, cyral/internal/repository/confauth/model.go, cyral/internal/repository/confauth/resource.go, cyral/internal/repository/confauth/resource_test.go, docs/resources/repository_conf_auth.md, docs/resources/repository_network_access_policy.md
Fix invalid repo TLS option check in `cyral_repository_conf_auth`.
All tests ran successfully in a `v4.16` CP:
```
make local/test
?       github.com/cyralinc/terraform-provider-cyral/cyral/core [no test files]
?       github.com/cyralinc/terraform-provider-cyral/cyral/core/types/operationtype     [no test files]
?       github.com/cyralinc/terraform-provider-cyral/cyral/core/types/resourcetype      [no test files]
=== RUN …
```
=> ENG-14351: Fix invalid TLS option check

docs/resources/repository_conf_auth.md, examples/resources/cyral_repository_conf_auth/resource.tf
Fix wrong documentation parameters in `cyral_repository_conf_auth`.
NA
=> Fix wrong doc parameters in repo conf auth

cyral/internal/sidecar/model.go, cyral/internal/sidecar/resource.go, cyral/internal/sidecar/resource_test.go, docs/resources/sidecar.md
[ENG-14011](https://cyralinc.atlassian.net/browse/ENG-14011): Add vault_integration_id field to cyral_sidecar resource in terraform provider
Running acceptance tests and testing the sidecar resource using local changes.
[ENG-14011]: https://cyralinc.atlassian.net/browse/ENG-14011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ENG-14011: Add vault_integration_id field to cyral_sidecar resource in terraform provider

docs/guides/iam_auth_rds_pg.md, docs/guides/mongodb_cluster_okta_idp.md, docs/guides/s3_browser_and_aws_cli.md, docs/guides/setup_cp_and_deploy_sidecar.md, docs/guides/smart_ports.md, docs/index.md, docs/resources/integration_logging.md
Update all references to the TF EC2 module to refer to the new major `v5`.
Depends on https://github.com/cyralinc/terraform-aws-sidecar-ec2/pull/118 and a new version `v5` of the module officially released.
NA
=> Update TF EC2 module to v5

docs/guides/mongodb_cluster_okta_idp.md, docs/guides/setup_cp_and_deploy_sidecar.md, docs/guides/smart_ports.md, examples/guides/iam_auth_rds_pg.tf, examples/guides/mongodb_cluster/okta_idp_sidecar.tf, examples/guides/s3_browser_and_aws_cli.tf, examples/guides/setup_cp_and_deploy_sidecar.tf, examples/guides/smart_ports_1.tf, examples/guides/smart_ports_2.tf, examples/resources/cyral_integration_logging/cloudwatch.tf, templates/index.md.tmpl
Fix several issues in the docs templates that prevented the generation of the correct docs. These files were missed in the `git add` in the previous commit in `main`.
NA
=> Fix docs templates
